spring:
  application:
    name: zuul-server
server:
  port: 8080
  servlet:
    context-path: /cloud
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555/cloud[/endpoint/]
zuul:
  routes:
    eureka-product-form-client: /form/**
    eureka-product-client: /products/**

# ribbon:
#   ReadTimeout: 60000
